
function varargout = contrast(varargin)
    % This GUI contains controls to change the values of CLAHE function.
    hContrastFigure = findall(0, 'tag', 'contrast');
    hMainFigure = findall(0, 'tag', 'maingui');
    
    %Start Singleton
    if (isempty(hMainFigure))
        fprintf('Warning: This instance can not run whitout first execute the primary GUI\n');
        return;
    elseif (isempty(hContrastFigure))
        % calculate the size and position in the screen of the GUI
        sizeOfScreen = get(0,'ScreenSize');
        position = sizeOfScreen;
        x = position(3)/5;
        y = position(4)/5;
        position(1) = x;
        position(2) = y;
        position(3) = position(3) - x - x;
        position(4) = position(4) - y - y;

        hContrastFigure = figure('position', position, ... 
                               'name', 'Contrast options', ... %'resize', 'off', ...
                               'numbertitle', 'off', 'dockcontrols', 'off', ...
                               'tag', 'contrast', 'menubar', 'none'); 
        % containers
        containerone = uiflowcontainer('units', 'norm', 'position', [0.03 0.03 0.94 0.2]);
        set(containerone,'FlowDirection','lefttoright', 'margin', 10);

        containertwo = uiflowcontainer('units', 'norm', 'position', [0.03 0.25 0.94 0.2]);
        set(containertwo,'FlowDirection','lefttoright', 'margin', 10);

        % contrast enhancement limit
        uicontrol(hContrastFigure, 'style', 'text', ...
                        'string', 'Contrast Enhancement Limit', ...
                        'units', 'normalized', ...
                        'position', [0.02 0.02 0.25 0.05],...
                        'parent', containertwo);

        h2 = uicontrol(hContrastFigure, 'style', 'slider', ...
                         'min', 0, 'max', 1, 'sliderstep', [0.05 0.01], ...
                         'callback', @celCallback, ...
                         'units', 'normalized', ...
                         'position', [0.28 0.02 0.60 0.05], ...
                         'parent', containertwo);
        set(h2, 'HeightLimits', [2, 50]);

        celval = uicontrol(hContrastFigure, 'style', 'text', ...
                            'string', '0.0', ...
                            'units', 'normalized', ...
                            'position', [0.89 0.02 0.09 0.05], ...
                            'parent', containertwo);
        
        % Number of tiles by row
        uicontrol(hContrastFigure, 'style', 'text', ...
                        'string', 'Tiles by Row', ...
                        'units', 'normalized', ...
                        'position', [0.02 0.18 0.25 0.05], ...
                        'parent', containerone);

        h5 = uicontrol(hContrastFigure, 'style', 'slider', ...
                         'min', 0, 'max', 1, 'sliderstep', [0.05 0.01], ...
                         'callback', @tilesByRow, ...
                         'units', 'normalized', ...
                         'position', [0.28 0.18 0.60 0.05], ...
                         'parent', containerone);
        set(h5, 'HeightLimits', [2, 50]);

        tbrowval = uicontrol(hContrastFigure, 'style', 'text', ...
                            'string', '0.0', ...
                            'units', 'normalized', ...
                            'position', [0.89 0.18 0.09 0.05], ...
                            'parent', containerone);
        
        %% Number of tiles by column
        %uicontrol(hContrastFigure, 'style', 'text', ...
        %                'string', 'Tiles by Column', ...
        %                'units', 'normalized', ...
        %                'position', [0.02 0.34 0.25 0.05]);

        %uicontrol(hContrastFigure, 'style', 'slider', ...
        %                 'min', 0, 'max', 10, 'sliderstep', [0 0.01], ...
        %                 'callback', @tilesByRow, ...
        %                 'units', 'normalized', ...
        %                 'position', [0.28 0.34 0.60 0.05]);

        %tbrowval = uicontrol(hContrastFigure, 'style', 'text', ...
        %                    'string', '0.0', ...
        %                    'units', 'normalized', ...
        %                    'position', [0.89 0.34 0.09 0.05]);
        %
        %% Number of bins
        %uicontrol(hContrastFigure, 'style', 'text', ...
        %                'string', 'Number of bins', ...
        %                'units', 'normalized', ...
        %                'position', [0.02 0.52 0.25 0.05]);

        %uicontrol(hContrastFigure, 'style', 'slider', ...
        %                 'min', 0, 'max', 1024, ...
        %                 'sliderstep', [0 0.01], ...
        %                 'callback', @tilesByRow, ...
        %                 'units', 'normalized', ...
        %                 'position', [0.28 0.52 0.60 0.05]);

        %tbrowval = uicontrol(hContrastFigure, 'style', 'text', ...
        %                    'string', '0.0', ...
        %                    'units', 'normalized', ...
        %                    'position', [0.89 0.52 0.09 0.05]);

        %% Distribution
        %uicontrol(hContrastFigure, 'style', 'text', ...
        %                'string', 'Distribution', ...
        %                'units', 'normalized', ...
        %                'position', [0.02 0.70 0.25 0.05]);

        %dist = uicontrol(hContrastFigure, 'style', 'popupmenu', ...
        %                 'string', {'uniform', 'rayleigh', 'exponential'}, ...
        %                 'units', 'normalized', ...
        %                 'position', [0.28 0.70 0.60 0.05]);

        %% Range
        %uicontrol(hContrastFigure, 'style', 'text', ...
        %                'string', 'Range', ...
        %                'units', 'normalized', ...
        %                'position', [0.02 0.88 0.25 0.05]);

        %dist = uicontrol(hContrastFigure, 'style', 'popupmenu', ...
        %                 'string', {'original', 'full'}, ...
        %                 'units', 'normalized', ...
        %                 'position', [0.28 0.88 0.60 0.05]);

        %% ---[ end of uicontrol section ] ---

        contrastGUIData.value = 100;
        setappdata(hContrastFigure, 'childGUI', contrastGUIData);
    else
        figure(hContrastFigure);
    end %end of Singleton
   
    % --------------------- Functions and Callbacks -------------------------

    function celCallback(hObject, eventdata)
        value = get(hObject, 'value');
        set(celval, 'string', value);
    end

    function tilesByRow(hObject, eventdata)
        value = get(hObject, 'value');
        set(tbrowval, 'string', value);
    end

end 

